version: 2 # use CircleCI 2.0
jobs: # a collection of steps
  build: # runs not using Workflows must have a `build` job as entry point
    working_directory: ~/-express-circle # directory where steps will run
    docker: # run the steps with Docker
      - image: circleci/ruby:2.2.1-node-browsers      
      
    steps: # a collection of executable commands 
      - checkout
      - run: bundle install --jobs=4 --retry=3 --path vendor/bundle    
      - run: bash <(curl -s https://scripts.scantist.com/staging/ci-circle-jar.sh)
    
